### ISSUE TITLE
I deserve.

### ISSUE THREAD

**Issue by luisvonmuller** [team-rustaceans/join#1]

**Comment by luisvonmuller** [comment]
My twith link: www.twitch.tv/luisvonmuller/ - My twitter for messagin: https://twitter.com/luisvonmuller

Most the time I stream when working, never planned. : >

**Comment by rochacbruno** [comment]
I already invited you! look at your twitch channel dashboard  :) you must have an invite under https://dashboard.twitch.tv/u/YOURUSERNAME/settings/channel
