### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by davidpdrsn** [team-rustaceans/join#3]
Twitch: twitch.tv/davidpdrsn
YouTube: youtube.com/channel/UCDmSWx6SK0zCU2NqPJ0VmDQ

My streams are mostly aimed at at beginner to intermediate. Currently doing a series on building a web app with wasm.

**Comment by rochacbruno** [comment]
Invited :)

**Comment by davidpdrsn** [comment]
Accepted, thanks!
