### ISSUE TITLE
Request to join (dakomz)

### ISSUE THREAD

**Issue by dakom** [team-rustaceans/join#4]
Heya!

I don't stream often, but might be picking it up again soon. The content is split between two things, both mostly in the wasm ecosystem. It's usually more about learning how to do things and getting stuck on stuff as opposed to say a tutorial style ;)

1. Dayjob stuff (regular dom)
2. Side-project stuff (gamedev)

twitch url: https://twitch.tv/dakomz

**Comment by rochacbruno** [comment]
Hi @dakom I am happy to invite you to the Rustaceans team, Does your channel has any recorded video? 

I followed you and I will be watching your next Rust stream so I can send the invite :) thanks

**Comment by dakom** [comment]
Hey @rochacbruno , cool :D I haven't been streaming as much lately, but will make sure to do a session in the not-too-distant future.

I guess Twitch doesn't hold onto video for past a couple weeks :\

**Comment by rochacbruno** [comment]
Invite sent! @dakom :)

**Comment by dakom** [comment]
Thanks, accepted :D
